### ISSUE TITLE
savedir not working on Windows

### ISSUE THREAD

**Issue by kwstat** [lian0090/FW#2]
I'm having a problem on Windows, in which the path separator can be either "\\" or "/".

When calling the function GibbsFWh0, I get this error:

dir.create(savedir) : 'c:\x' already exists

When I dig further, I find:

Browse[2]> getwd()
[1] "c:/x"

Browse[2]> saveAt
[1] "c:\x\/"

I think you need to be careful when creating the saveAt variable.

**Comment by lian0090** [comment]
The issuer has been resolved. Thanks!
