### ISSUE TITLE
Would be nice to allow factors for VAR, ENV

### ISSUE THREAD

**Issue by kwstat** [lian0090/FW#3]
The documentation does clearly state that VAR and ENV need to be character.  It would be nice to allow them to be factors, since data stored in dataframes is almost always factor, not character.

``` r
library(agridat)
data(digby.jointregression)
digby <- digby.jointregression
# Change factors to character
digbyc <- transform(digby, gen=as.character(gen), env=as.character(env))

library(FW)
m0 <- FW(y=digbyc$yield, VAR=digbyc$gen, ENV=digbyc$env, method="OLS")
plot(m0) # Looks right

m1 <- FW(y=digby$yield, VAR=digby$gen, ENV=digby$env, method="OLS")
plot(m1) # Clearly wrong
```

**Comment by lian0090** [comment]
Dear Kevin,

Thank you so much for these helpful suggestions! I have updated the package and now it works well on factor VAR and factor ENV.

The saveAt is also updated for Windows.

I will do more tests tomorrow to make sure everything else works as usual and let you know.

Thanks!

Lian

**Comment by lian0090** [comment]
The issue has been resolved. Thanks again!
